recipe_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('recipes/', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import recipes_home
from .views import RecipeListView
from .views import RecipeDetailView
from .views import records

app_name = 'recipes'

urlpatterns = [
    path('', recipes_home, name='home'),
    path('list/', RecipeListView.as_view(), name='list'),
    path('list/<pk>', RecipeDetailView.as_view(), name='detail'),
    path('search/', records, name='search')
]

recipes/models.py
from django.db import models
from django.shortcuts import reverse


class Recipe(models.Model):
    name = models.CharField(max_length=120)
    cooking_time = models.FloatField(help_text='in minutes')
    ingredients = models.CharField(
        max_length=350, help_text="Input must be separated by commas exp(Eggs, Soy, Milk)")
    description = models.TextField()
    pic = models.ImageField(upload_to='recipes', default='no_picture.png')

    def calc_difficulty(self):
        ingredients = self.ingredients.split(', ')
        if self.cooking_time < 15 and len(ingredients) < 7:
            difficulty = 'Easy'
        elif self.cooking_time < 15 and len(ingredients) >= 7:
            difficulty = 'Medium'
        elif self.cooking_time >= 15 and len(ingredients) < 7:
            difficulty = 'Intermediate'
        elif self.cooking_time >= 15 and len(ingredients) >= 7:
            difficulty = 'Hard'
        return difficulty

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('recipes:detail', kwargs={'pk': self.pk})

recipes/forms.py
from django import forms

CHART__CHOICES = (
    ('#1', 'Bar chart'),
    ('#2', 'Pie chart'),
    ('#3', 'Line chart')
)

DIFFIC__CHOICES = (
    ('#1', 'Easy'),
    ('#2', 'Medium'),
    ('#3', 'Intermediate'),
    ('#4', 'Hard')
)


class RecipeSearchForm(forms.Form):
    recipe_diff = forms.ChoiceField(choices=DIFFIC__CHOICES)
    chart_type = forms.ChoiceField(choices=CHART__CHOICES)

recipe_project/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm


def login_view(request):
    error_message = None
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('/list')
        else:
            error_message = "Something went wrong, try again."

    context = {
        'form': form,
        'error_message': error_message
    }

    return render(request, 'auth/login.html', context)


def logout_view(request):
    logout(request)

    return render(request, 'auth/success.html')

recipes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Recipe
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import RecipeSearchForm

import pandas as pd
from .utils import get_recipename_from_id, get_chart


class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/recipes_list.html'


class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipes/detail.html'


def recipes_home(request):
    return render(request, 'recipes/recipes_home.html')


@login_required
def records(request):
    return render(request, 'recipes/recipes_list.html')


def records(request):
    form = RecipeSearchForm(request.POST or None)
    recipe_df = None
    recipe_diff = None
    chart = None
    qs = None
    if request.method == 'POST':
        recipe_diff = request.POST.get('recipe_diff')
        chart_type = request.POST.get('chart_type')

        if recipe_diff == '#1':
            recipe_diff = 'Easy'
        if recipe_diff == '#2':
            recipe_diff = 'Medium'
        if recipe_diff == '#3':
            recipe_diff = 'Intermediate'
        if recipe_diff == '#4':
            recipe_diff = 'Hard'

        qs = Recipe.objects.all()
        id_searched = []
        for obj in qs:
            diff = obj.calc_difficulty()
            if diff == recipe_diff:
                id_searched.append(obj.id)

        qs = qs.filter(id__in=id_searched)

        if qs:
            recipe_df = pd.DataFrame(qs.values())
            chart = get_chart(chart_type, recipe_df,
                              labels=recipe_df['name'].values)
            recipe_df = recipe_df.to_html()

    context = {
        'form': form,
        'recipe_df': recipe_df,
        'recipe_diff': recipe_diff,
        'chart': chart,
        'qs': qs
    }
    return render(request, 'recipes/search.html', context)

recipes/templates/recipes/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'recipes/css/styles.css' %}"
    />
    <title>Recipe Detail</title>
    <link
      rel="shortcut icon"
      href="{% static 'recipes/images/favicon.png' %}"
    />
    <style type="text/css">
      body {
        background: url("{% static 'recipes/images/background.jpg' %}")
          no-repeat fixed;
        background-size: cover;
        display: flex;
        flex-direction: column;
        align-items: center;
      }
    </style>
  </head>
  <body>
    <div class="nav_bar">
      <a class="login_btn" href="{%url 'recipes:list' %}">Recipes</a>
      <a class="login_btn" href="{%url 'recipes:search' %}">Search</a>
      <a class="login_btn" href="{%url 'logout' %}">Logout</a>
    </div>
    <h2 class="details_name">{{object.name}}</h2>
    <img class="recipe_img_detail" src="{{object.pic.url}}" />
    <div class="details_discrip">
      <b>Name: </b> {{object.name}} <br />
      <b>Description: </b> {{object.description}} <br />
      <b>Cooking Time: </b> {{object.cooking_time}} <br />
      <b>Difficulty: </b> {{object.calc_difficulty}} <br />
      <b>Ingredients: </b> {{object.ingredients}} <br />
    </div>
    <a href="{% url 'recipes:list' %}" class="login_btn">Back</a>
    <script>
      function goBack() {
        window.history.back();
      }
    </script>
  </body>
</html>

recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width= , initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'recipes/css/styles.css' %}"
    />
    <link
      rel="shortcut icon"
      href="{% static 'recipes/images/favicon.png' %}"
    />
    <title>Recipe Home</title>
    <style type="text/css">
      body {
        background: url("{% static 'recipes/images/background.jpg' %}")
          no-repeat fixed;
        background-size: cover;
        display: flex;
        flex-direction: column;
        align-items: center;
      }
    </style>
  </head>
  <body>
    <h1 class="details_name">Welcome to Recipe App</h1>
    <br />
    <h3 class="details_discrip">
      Log in to your account to see our list of recipes
    </h3>
    <a href="{%url 'login' %}" class="login_btn"> Login </a>
  </body>
</html>

recipes/templates/recipes/recipes_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'recipes/css/styles.css' %}"
    />
    <title>Recipe List</title>
    <link
      rel="shortcut icon"
      href="{% static 'recipes/images/favicon.png' %}"
    />
    <style type="text/css">
      body {
        background: url("{% static 'recipes/images/background.jpg' %}")
          no-repeat fixed;
        background-size: cover;
      }
      @media screen and (max-width: 600px) {
        .recipe_grid,
        .recipe_name {
          display: flex;
          flex-direction: column;
          flex-wrap: wrap;
          justify-content: center;
          padding: 10px 0;
          min-height: 100%;
        }
      }
      @media screen and (min-width: 600px) {
        .recipe_name {
          display: flex;
          flex-direction: column-reverse;
        }
        .recipe_grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
        }
      }
    </style>
  </head>
  <body>
    <div class="nav_bar">
      <a class="login_btn" href="{%url 'recipes:list' %}">Recipes</a>
      <a class="login_btn" href="{%url 'recipes:search' %}">Search</a>
      <a class="login_btn" href="{%url 'logout' %}">Logout</a>
    </div>
    <div class="recipe_grid">
      {% for object in object_list %}
      <div>
        <h3 style="text-align: center">
          <a class="recipe_name" href="{{object.get_absolute_url}}">
            {{object.name}}
          </a>
        </h3>
        <img class="recipe_img" src="{{object.pic.url}}" />
        <div class="recipe_short">
          <b>Cooking Time: </b> {{object.cooking_time}} min <br />
          <b>Difficulty: </b> {{object.calc_difficulty}} <br />
        </div>
      </div>
      {% endfor %}
    </div>
  </body>
</html>

recipes/templates/recipes/search.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'recipes/css/styles.css' %}"
    />
    <title>Recipe Search</title>
    <link
      rel="shortcut icon"
      href="{% static 'recipes/images/favicon.png' %}"
    />
    <style type="text/css">
      body {
        background: url("{% static 'recipes/images/background.jpg' %}")
          no-repeat fixed;
        background-size: cover;
        color: black;
        display: flex;
        flex-direction: column;
        align-items: center;
      }
    </style>
  </head>

  <hr />
  <body>
    <div class="nav_bar">
      <a class="login_btn" href="{%url 'recipes:list' %}">Recipes</a>
      <a class="login_btn" href="{%url 'recipes:search' %}">Search</a>
      <a class="login_btn" href="{%url 'logout' %}">Logout</a>
    </div>
    <h1 class="details_name">Search for recipes</h1>
    <hr />
    <form class="login_form" action="" method="POST">
      {% csrf_token %} {{form}}
      <button class="login_btn" submit>Search</button>
    </form>
    <div class="search">
      <br />
      <br />
      {% if recipe_df %} {{recipe_df|safe}}
      <br />
      <img alt="chart" src="data:image/png;base64, {{chart|safe}}" />
      {% else %}
      <h3 class="recipe_short">
        No data found, try to look for something else.
      </h3>
      {% endif %}
    </div>
    <br />
    <a href="{% url 'recipes:list' %}" class="login_btn">Back</a>
    <script>
      function goBack() {
        window.history.back();
      }
    </script>
  </body>
</html>

src/recipes/templates/recipes/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Recipe Detail</title>
    <link
      rel="shortcut icon"
      href="{% static 'recipes/images/favicon.png' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'recipes/css/styles.css' %}"
    />
    <style type="text/css">
      body {
        background: url("{% static 'recipes/images/background.jpg' %}")
          no-repeat fixed;
        background-size: cover;
        display: flex;
        flex-direction: column;
        align-items: center;
      }
    </style>
  </head>
  <body>
    <h2>{{object.name}}</h2>
    <img src="{{object.pic.url}}" />
    <div>
      <b>Name: </b> {{object.name}} <br />
      <b>Description: </b> {{object.description}} <br />
      <b>Cooking Time: </b> {{object.cooking_time}} <br />
      <b>Difficulty: </b> {{object.calc_difficulty}} <br />
      <b>Ingredients: </b> {{object.ingredients}} <br />
    </div>
  </body>
</html>